# This is a basic workflow that is manually triggered

name: Manual workflow


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      filename:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Snippet Name'
        # Default value if no value is explicitly provided
        default: 'my-snippet'
        # Input has to be provided for the workflow to run
        required: true


jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: '${{ github.event.inputs.filename }}.mdx'
          FILE_DATA: "file content"
